services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - 80:80
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.prod
    ports:
      - 8000:8000
    environment:
      DB_URL: mongodb://db
   