services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 80:80
    # volumes:
    #   - ./frontend:/app  
  backend:
    build: ./backend
    ports:
      - 8000:8000
    environment:
      DB_URL: mongodb://db
    # volumes:
    #   - ./backend:/app
    # this property will overwrite the CMD command of Dockerfile to this service  
    # command: ./docker-entrypoint.sh 

volumes:
  reactpythonapp:    