FROM tiangolo/uvicorn-gunicorn:python3.11-slim

RUN python -m venv /virtualenv && . /virtualenv/bin/activate

COPY pythonRequirements.prod.txt /tmp/pythonRequirements.prod.txt
RUN pip install --no-cache -r /tmp/pythonRequirements.prod.txt

COPY . /backend

WORKDIR /backend
EXPOSE 8000

CMD ["python3", "main.py"]